---

- name: Ensure postgresql signing key directory exists
  ansible.builtin.file:
    path: "{{ __pgbackrest_signing_key_dest | dirname }}"
    state: directory
    mode: '0755'

- name: Add postgresql signing key
  ansible.builtin.get_url:
    url: "{{ __pgbackrest_signing_key }}"
    dest: "{{ __pgbackrest_signing_key_dest }}"
    mode: '0644'
    force: true

- name: Add postgresql repository
  ansible.builtin.apt_repository:
    repo: "{{ __pgbackrest_repository }}"
    update_cache: true

- name: Install pgbackrest
  ansible.builtin.apt:
    name: pgbackrest={{ pgbackrest_version }}*
