---

- name: Add postgresql signing key
  ansible.builtin.get_url:
    url: "{{ __pgbackrest_signing_key }}"
    dest: /etc/apt/trusted.gpg.d/pgbackrest.asc
    mode: '0644'
    force: true

- name: Add postgresql repository
  ansible.builtin.apt_repository:
    repo: "{{ __pgbackrest_repository }}"
    update_cache: true

- name: Install pgbackrest
  ansible.builtin.apt:
    name: pgbackrest={{ pgbackrest_version }}*
